start "" "F:\windows\Snipaste-2.8.5-Beta-x64\Snipaste.exe"
start "" "F:\windows\Stretchly\Stretchly.exe"
start "" "F:\windows\FirefoxPortable\FirefoxPortable.exe"
start "" "C:\Users\user\AppData\Local\PowerToys\PowerToys.exe"
start "" "F:\windows\Google Search_v2.ahk"